import { AxiosHeaders } from "axios";
import { SecurityHandlerBase } from "./SecurityHandlerBase";
export declare class WebsiteSignUpSecurityHandle extends SecurityHandlerBase {
    encodeRequest(request: string, headers: Map<string, string>): Promise<string>;
    private _serverEncryptionKey;
    private _clientDecryptionKey;
    private _email;
    private _token;
    private _password;
    private _firstName;
    private _middleName;
    private _lastName;
    private _phoneNumber;
    private _document;
    private _businessType;
    private _businessLegalName;
    private _serviceCategory;
    private _businessDescription;
    private _socialSecurityNumber;
    private _ein;
    private _address;
    private _city;
    private _state;
    private _zipCode;
    private _file;
    private _fileNonce;
    private _walletAddress;
    private _walletType;
    private _defaultCurrency;
    get defaultCurrency(): string;
    set defaultCurrency(dc: string);
    get walletAddress(): string;
    get walletType(): string;
    set walletAddress(wa: string);
    set walletType(wt: string);
    get fileNonce(): string;
    set fileNonce(fn: string);
    get firstName(): string;
    set firstName(value: string);
    get middleName(): string;
    set middleName(value: string);
    get lastName(): string;
    set lastName(value: string);
    get phoneNumber(): string;
    set phoneNumber(value: string);
    get document(): string;
    set document(value: string);
    get businessType(): string;
    set businessType(value: string);
    get businessLegalName(): string;
    set businessLegalName(value: string);
    get serviceCategory(): string;
    set serviceCategory(value: string);
    get businessDescription(): string;
    set businessDescription(value: string);
    get socialSecurityNumber(): string;
    set socialSecurityNumber(value: string);
    get ein(): string;
    set ein(value: string);
    get address(): string;
    set address(value: string);
    get city(): string;
    set city(value: string);
    get state(): string;
    set state(value: string);
    get zipCode(): string;
    set zipCode(value: string);
    set password(p: string);
    get password(): string;
    get file(): string;
    set file(f: string);
    constructor(email: string, rsaKeyPair: {
        publicKey: string;
        privateKey: string;
    }, token: string);
    decodeResponse(response: string, headers?: AxiosHeaders): Promise<string>;
    createHeaders(): Promise<Map<string, string>>;
}
