import { FluxType } from "./FluxType";
import { IBankAccount } from "./IBankAccount";
import { CustomerSensitiveData } from "./CustomerSensitiveData";
export declare class BankAccount extends FluxType implements IBankAccount {
    obName: string;
    objectType: string;
    serialize(): {
        objectType: string;
        lastFour: string;
        accountNumber: string;
        oneTimeUseToken: string;
        routingNumber: string;
        accountType: string;
        bankName: string;
        email: string;
        address1: string;
        city: string;
        state: string;
        country: string;
        zipCode: string;
    };
    constructor(c: Partial<IBankAccount>);
    lastFour: string;
    oneTimeUseToken: string;
    bankName: string;
    routingNumber: string;
    bankBrand: string;
    email: string;
    accountNumber: string;
    accountType: string;
    accountSession: string;
    metadata: string;
    firstName: string;
    lastName: string;
    address1: string;
    city: string;
    state: string;
    country: string;
    zipCode: string;
    static parseCustomerSensitiveData(csd: CustomerSensitiveData): BankAccount;
    validateBankAccount(): Promise<void>;
    getDispName(): string;
}
