import { Address } from "./Address";
import { CustomerSensitiveData } from "./CustomerSensitiveData";
import { FluxType } from "./FluxType";
import { ICard } from "./ICard";
export declare class Card extends FluxType implements ICard {
    obName: string;
    objectType: string;
    constructor(c: Partial<ICard>);
    accountSession: string;
    expiryDate: string;
    address: Address;
    cardNumber: string;
    cvv: string;
    cardBrand: string;
    lastFour: string;
    address1: string;
    address2: string;
    city: string;
    state: string;
    zip: string;
    country: string;
    uniqueId: string;
    metadata: string;
    firstName: string;
    lastName: string;
    id: number;
    payType: string;
    serialize(): {
        objectType: string;
        lastFour: string;
        cardBrand: string;
        address1: string;
        address2: string;
        city: string;
        state: string;
        zip: string;
        country: string;
        expiryDate: string;
        cardNumber: string;
        cvv: string;
        firstName: string;
        lastName: string;
        uniqueId: string;
        metadata: string;
    };
    getDispName(): string;
    static createInstanceLazy(acc: Partial<ICard>): Promise<Card>;
    static parseCustomerSensitiveData(csd: CustomerSensitiveData): Card;
}
