import { FluxType } from './FluxType';
import { IPaymentLink } from './IPaymentLink';
import { Product } from './Product';
import { Currency } from './Currency';
import { Wallet } from './Wallet';
export declare class PaymentLink extends FluxType implements IPaymentLink {
    obName: string;
    serialize(): {
        id: number;
        metadata: string;
        objectType: string;
        uniqueId: string;
        paymentLink: string;
        accountId: number;
        products: Product[];
        emailNotificationEnabled: boolean;
        serviceFee: number;
        taxRatesId: number;
        wallets: Wallet[];
        currencies: Currency[];
        accountEmail: string;
        confidenceLevel: number;
        requireShippingAddress: boolean;
        requireAccountInformation: boolean;
        status: string;
        currentStatus: any;
        redirectUrl: string;
        oneTimeUse: boolean;
    };
    wallets: Wallet[];
    id: number;
    metadata: string;
    uniqueId: string;
    serviceFee: number;
    taxRatesId: number;
    requireAccountInformation: boolean;
    confidenceLevel: number;
    currentStatus: any;
    taxAmount: number;
    paymentLink: string;
    requireShippingAddress: boolean;
    redirectUrl: string;
    oneTimeUse: boolean;
    emailNotificationEnabled: boolean;
    accountId: number;
    status: string;
    accountEmail: string;
    products: Product[];
    currencies: Currency[];
    protected objectType: string;
    constructor(pl?: Partial<PaymentLink>);
    static createInstanceLazy(acc: Partial<IPaymentLink>): Promise<PaymentLink>;
    static createInstanceSafe(acc: Partial<IPaymentLink>): Promise<PaymentLink>;
}
