import { Currency } from './Currency';
import { Wallet } from './Wallet';

export interface IMerchant {
    id: number;
    merchantApproved: boolean;
    isTaxEnabled: boolean;
    enableACH: boolean;
    passwordHash: string;
    ssnToken: string;
    displayEmail: string;
    firstName: string;
    middleName: string;
    lastName: string;
    businessType: string;
    ein: string;
    creationTime: Date;
    runningBalance: number;
    pendingBalance: number;
    settledBalance: number;
    failedLoginAttempts: number;
    streetAddress: string;
    country: string;
    zipcode: string;
    processingFeeAuthAmount: number;
    addressState: string;
    defaultCurrency: string;
    city: string;
    nabMerchantkey: number;
    creditCardCost: number;
    debitCardCost: number;
    visaMoneyTransferCost: number;
    processingFeeEnabled: boolean;
    processingFeeRate: number;
    achProcessingFeeRate: number;
    cryptoProcessingFeeRate: number;
    serviceFeeRate: number;
    masterCardMoneyTransferCost: number;
    achCost: number;
    phoneNumber: string;
    businessName: string;
    businessDescription: string;
    serviceCategory: string;
    documentName: string;
    documentToken: string;
    processingFeeFlatAmount: number;
    merchantLogo: string;
    paymentLinkColor: string;
    defaultTaxRateId: number;
    cryptoWallets: Wallet[];
    cryptoCurrencies: Currency[];
}
