import { FluxType } from "./FluxType";
import { IForthClientMapping } from "./IForthClientMapping";
export declare class ForthClientMapping extends FluxType implements IForthClientMapping {
    obName: string;
    getDispName(): string;
    serialize(): {
        id: number;
        uniqueId: string;
        merchantId: number;
        credentialsId: number;
        forthClientId: number;
        forthCompanyId: number;
        forthClientEmail: string;
        forthClientFirstName: string;
        forthClientLastName: string;
        forthClientPhone: string;
        fluxAccountId: number;
        cardIntakePaymentLinkId: number;
        intakeSentAt: number;
        intakeCompletedAt: number;
        paymentMethodOnFileId: number;
        enrollmentStatus: string;
        enrollmentPaused: boolean;
        enrollmentDropped: boolean;
        enrollmentGraduated: boolean;
        waitingForCardRefresh: boolean;
        lastChargedAt: number;
        lastChargeStatus: string;
        lastChargeError: string;
        paused: boolean;
        activeStatus: boolean;
        metadata: string;
        version: number;
        objectType: string;
    };
    id: number;
    uniqueId: string;
    merchantId?: number;
    credentialsId?: number;
    forthClientId?: number;
    forthCompanyId?: number;
    forthClientEmail?: string;
    forthClientFirstName?: string;
    forthClientLastName?: string;
    forthClientPhone?: string;
    fluxAccountId?: number;
    cardIntakePaymentLinkId?: number;
    intakeSentAt?: number;
    intakeCompletedAt?: number;
    paymentMethodOnFileId?: number;
    enrollmentStatus?: string;
    enrollmentPaused?: boolean;
    enrollmentDropped?: boolean;
    enrollmentGraduated?: boolean;
    waitingForCardRefresh?: boolean;
    lastChargedAt?: number;
    lastChargeStatus?: string;
    lastChargeError?: string;
    paused?: boolean;
    activeStatus?: boolean;
    metadata?: string;
    version?: number;
    protected objectType: string;
    constructor(data?: Partial<IForthClientMapping>);
    static createInstanceLazy(data: Partial<IForthClientMapping>): Promise<ForthClientMapping>;
    static createInstanceSafe(data: Partial<IForthClientMapping>): Promise<ForthClientMapping>;
}
