import { Currency } from "./Currency";
import { Product } from "./Product";
import { Wallet } from "./Wallet";
export interface IPaymentLink {
    id?: number;
    metadata?: string;
    uniqueId?: string;
    isReusable?: boolean;
    redirectUrl: string;
    minutesToExpire: number;
    oneTimeUse: boolean;
    enableCrypto: boolean;
    disableACH: boolean;
    disableCard: boolean;
    taxRatesId: number;
    discountId?: number;
    discountAmount?: number;
    discountName?: string;
    perProductDiscountTotal?: number;
    originalSubtotal?: number;
    requireShippingAddress: boolean;
    reusableLinkId: number;
    currentStatus: string;
    serviceFeeRate: number;
    liveStatus?: any;
    wallets?: Wallet[];
    currencies?: Currency[];
    products?: Product[];
    requireAccountInformation: boolean;
    confidenceLevel: number;
    removeOnSuccess?: any;
    paymentLink?: string;
    accountId?: number;
    emailNotificationDisabled: boolean;
    isInvoice?: boolean;
    dueDate?: number;
    qbInvoiceId?: string;
    hasBeenSyncedToQuickbooks?: boolean;
    processingFeeInversion: boolean;
    isProcessingFeeEnabled?: boolean;
    processingFeeInversionAch?: boolean;
    processingFeeInversionCard?: boolean;
    isProcessingFeeEnabledAch?: boolean;
    isProcessingFeeEnabledCard?: boolean;
    name?: string;
    memo?: string;
}
