import { Account } from "./Account";
import { Address } from "./Address";
import { PaymentMethod } from "./PaymentMethod";
import { Product } from "./Product";
export interface ITransaction {
    account: Account;
    paymentMethod: PaymentMethod;
    isReprocessRequest?: boolean;
    isRefund?: boolean;
    id: number;
    uniqueId: string;
    taxRate?: number;
    taxRateId: number;
    chainNumber: number;
    paymentLinkId: number;
    defaultCurrencyAmount: number;
    confidenceLevel: number;
    currency: string;
    approvalStatus: string;
    txnHash: string;
    transactionType: string;
    currencyId: number;
    shippingAddress: Address;
    products: Product | Product[];
    inventoryOnlyOrder?: boolean;
    accountSession?: string;
    oneTimeUseToken?: string;
    consentTermsAccepted?: boolean;
    consentTermsTextSnapshot?: string;
    consentRefundPolicySnapshot?: string;
    consentRecurringAuthAccepted?: boolean;
    consentRecurringAuthText?: string;
    consentDeviceFingerprint?: string;
    consentCheckoutSessionId?: string;
    hasBeenSyncedToQuickbooks?: boolean;
    quickbooksTransactionId?: string;
    quickbooksSyncDate?: number;
    cardBrandId?: string;
    customerEmail?: string;
    customerFirstName?: string;
    customerLastName?: string;
    customerPhone?: string;
    processorError?: string;
    gatewayResponse?: string;
    /** PCI-permitted truncation only — last four digits, never a full PAN. */
    cardLastFour?: string;
    /** PCI-permitted truncation only — BIN (first six), never a full PAN. */
    cardBin?: string;
    approvalCode?: string;
    avsCode?: string;
    cvvResult?: string;
    networkTransactionId?: string;
    retrievalReferenceNumber?: string;
    reconciliationId?: string;
    gatewayRequestId?: string;
    commerceIndicator?: string;
    initiatorType?: string;
    credentialStoredOnFile?: string;
    storedCredentialUsed?: boolean;
    previousTransactionIdSent?: string;
    entryMethod?: string;
    customerUserAgent?: string;
    customerAcceptLanguage?: string;
    deviceFingerprint?: string;
    checkoutSessionId?: string;
    termsAcceptedAt?: number;
    termsTextHash?: string;
    refundPolicyHash?: string;
    recurringAuthAcceptedAt?: number;
    achAuthAcceptedAt?: number;
    emailVerifiedAt?: number;
    /** JSON: line1,line2,city,state,zip,country,placeId,lat,lng */
    billingAddressSnapshot?: string;
    fulfillmentCarrier?: string;
    fulfillmentTracking?: string;
    shippedAt?: number;
    deliveredAt?: number;
    /** Set on REFUND rows. */
    refundReason?: string;
    evidencePacketS3Key?: string;
    evidencePacketJsonS3Key?: string;
    evidencePacketSha256?: string;
    evidencePacketSealedAt?: number;
    evidencePacketVersion?: number;
    /** PENDING | SEALED | FAILED | BACKFILL */
    evidencePacketStatus?: string;
    evidenceRetainUntil?: number;
    evidenceLegalHold?: boolean;
}
