import { Account } from "./Account";
import { Address } from "./Address";
import { PaymentMethod } from "./PaymentMethod";
import { Product } from "./Product";
export interface ITransaction {
    account: Account;
    paymentMethod: PaymentMethod;
    isReprocessRequest?: boolean;
    isRefund?: boolean;
    id: number;
    uniqueId: string;
    taxRate?: number;
    taxRateId: number;
    chainNumber: number;
    paymentLinkId: number;
    defaultCurrencyAmount: number;
    confidenceLevel: number;
    currency: string;
    approvalStatus: string;
    txnHash: string;
    currencyId: number;
    shippingAddress: Address;
    products: Product | Product[];
    inventoryOnlyOrder?: boolean;
    accountSession?: string;
    oneTimeUseToken?: string;
    hasBeenSyncedToQuickbooks?: boolean;
    quickbooksTransactionId?: string;
    quickbooksSyncDate?: number;
}
