import { FluxType } from "./FluxType";
import { IMerchantForthCredentials } from "./IMerchantForthCredentials";
export declare class MerchantForthCredentials extends FluxType implements IMerchantForthCredentials {
    obName: string;
    getDispName(): string;
    serialize(): {
        id: number;
        uniqueId: string;
        merchantId: number;
        label: string;
        forthCompanyId: number;
        forthCompanyName: string;
        forthCompanyContactName: string;
        forthCompanyEmail: string;
        forthAccessTokenExpiresAt: number;
        notificationEmail: string;
        autoChargeEnabled: boolean;
        paused: boolean;
        lastPollAt: number;
        lastClientWatermark: number;
        lastDebitWatermark: number;
        lastHoldPollAt: number;
        lastCompanyRefreshAt: number;
        consecutivePollFailures: number;
        pollBackoffUntil: number;
        refreshingAt: number;
        activeStatus: boolean;
        metadata: string;
        version: number;
        objectType: string;
    };
    id: number;
    uniqueId: string;
    merchantId?: number;
    label?: string;
    forthCompanyId?: number;
    forthCompanyName?: string;
    forthCompanyContactName?: string;
    forthCompanyEmail?: string;
    forthAccessTokenExpiresAt?: number;
    notificationEmail?: string;
    autoChargeEnabled?: boolean;
    paused?: boolean;
    lastPollAt?: number;
    lastClientWatermark?: number;
    lastDebitWatermark?: number;
    lastHoldPollAt?: number;
    lastCompanyRefreshAt?: number;
    consecutivePollFailures?: number;
    pollBackoffUntil?: number;
    refreshingAt?: number;
    activeStatus?: boolean;
    metadata?: string;
    version?: number;
    protected objectType: string;
    constructor(data?: Partial<IMerchantForthCredentials>);
    static createInstanceLazy(data: Partial<IMerchantForthCredentials>): Promise<MerchantForthCredentials>;
    static createInstanceSafe(data: Partial<IMerchantForthCredentials>): Promise<MerchantForthCredentials>;
}
