import { BaseQuery } from "./BaseQuery";
import { IMerchantQuery } from "./IMerchantQuery";
import { Merchant } from "./Merchant";
/**
 * This is an object that is used to query for merchants.
 */
export declare class MerchantQuery extends BaseQuery<Merchant> {
    serialize(): {
        id: number;
        merchantApproved: boolean;
        isTaxEnabled: boolean;
        passwordHash: string;
        ssnToken: string;
        firstName: string;
        middleName: string;
        lastName: string;
        businessType: string;
        ein: string;
        createdAt: number;
        creationTime: Date;
        runningBalance: number;
        pendingBalance: number;
        settledBalance: number;
        failedLoginAttempts: number;
        streetAddress: string;
        country: string;
        zipcode: string;
        addressState: string;
        defaultCurrency: string;
        city: string;
        nabMerchantkey: number;
        creditCardCost: number;
        debitCardCost: number;
        visaMoneyTransferCost: number;
        masterCardMoneyTransferCost: number;
        achCost: number;
        phoneNumber: string;
        businessName: string;
        businessDescription: string;
        serviceCategory: string;
        documentName: string;
        documentToken: string;
        objectType: string;
    };
    id: number;
    merchantApproved: boolean;
    isTaxEnabled: boolean;
    passwordHash: string;
    ssnToken: string;
    firstName: string;
    middleName: string;
    lastName: string;
    businessType: string;
    ein: string;
    creationTime: Date;
    runningBalance: number;
    pendingBalance: number;
    settledBalance: number;
    failedLoginAttempts: number;
    streetAddress: string;
    country: string;
    zipcode: string;
    addressState: string;
    defaultCurrency: string;
    city: string;
    nabMerchantkey: number;
    creditCardCost: number;
    debitCardCost: number;
    visaMoneyTransferCost: number;
    masterCardMoneyTransferCost: number;
    achCost: number;
    phoneNumber: string;
    businessName: string;
    businessDescription: string;
    serviceCategory: string;
    documentName: string;
    documentToken: string;
    objectType: string;
    constructor(tokQ?: IMerchantQuery);
    static createQuery(ipq: IMerchantQuery): MerchantQuery;
}
