import { FluxType } from './FluxType';
export declare class ObjectCounts extends FluxType {
    obName: string;
    getDispName(): string;
    serialize(): {
        id: number;
        uniqueid: string;
        metadata: string;
        version: number;
        email: string;
        account: number;
        wallet: number;
        walletLimit: number;
        address: number;
        product: number;
        currency: number;
        accountaddress: number;
        paymentmethod: number;
        token: number;
        accountLimit: number;
        addressLimit: number;
        productLimit: number;
        accountaddressLimit: number;
        taxratesLimit: number;
        taxrates: any;
        paymentmethodLimit: number;
        currencyLimit: number;
        tokenLimit: number;
        objectType: string;
    };
    wallet: number;
    walletLimit: number;
    id: number;
    currencyLimit: number;
    currency: number;
    uniqueid: string;
    metadata: string;
    version: number;
    email: string;
    account: number;
    address: number;
    product: number;
    accountaddress: number;
    paymentmethod: number;
    token: number;
    accountLimit: number;
    addressLimit: number;
    productLimit: number;
    accountaddressLimit: number;
    taxratesLimit: number;
    taxrates: any;
    paymentmethodLimit: number;
    tokenLimit: number;
    protected objectType: string;
    constructor(objectCounts?: Partial<ObjectCounts>);
}
