import { FluxType } from "./FluxType";
import { IPaymentMethodOnFile } from "./IPaymentMethodOnFile";
export declare class PaymentMethodOnFile extends FluxType implements IPaymentMethodOnFile {
    obName: string;
    getDispName(): string;
    serialize(): {
        id: number;
        uniqueId: string;
        merchantId: number;
        accountId: number;
        accountUniqueId: string;
        customerSensitiveDataId: number;
        customerSensitiveDataUniqueId: string;
        paymentLinkId: number;
        payType: string;
        lastFour: string;
        cardBrand: string;
        zeroDollarAuthTxnId: number;
        authRunAt: number;
        termsTextSnapshot: string;
        termsAcceptedAt: number;
        termsIp: string;
        termsUserAgent: string;
        activeStatus: boolean;
        metadata: string;
        version: number;
        objectType: string;
    };
    id: number;
    uniqueId: string;
    merchantId?: number;
    accountId?: number;
    accountUniqueId?: string;
    customerSensitiveDataId?: number;
    customerSensitiveDataUniqueId?: string;
    paymentLinkId?: number;
    payType?: string;
    lastFour?: string;
    cardBrand?: string;
    zeroDollarAuthTxnId?: number;
    authRunAt?: number;
    termsTextSnapshot?: string;
    termsAcceptedAt?: number;
    termsIp?: string;
    termsUserAgent?: string;
    activeStatus?: boolean;
    metadata?: string;
    version?: number;
    protected objectType: string;
    constructor(data?: Partial<IPaymentMethodOnFile>);
    static createInstanceLazy(data: Partial<IPaymentMethodOnFile>): Promise<PaymentMethodOnFile>;
    static createInstanceSafe(data: Partial<IPaymentMethodOnFile>): Promise<PaymentMethodOnFile>;
}
