import { FluxType } from './FluxType';
import { IPaymentLink } from './IPaymentLink';
import { Product } from './Product';
import { Currency } from './Currency';
import { Wallet } from './Wallet';
export declare class PaymentLink extends FluxType implements IPaymentLink {
    obName: string;
    getDispName(): string;
    serialize(): {
        id: number;
        metadata: string;
        objectType: string;
        uniqueId: string;
        paymentLink: string;
        accountId: number;
        createdAt: number;
        products: Product[];
        enableCrypto: boolean;
        emailNotificationDisabled: boolean;
        updateAccInfo: boolean;
        updateAddInfo: boolean;
        serviceFeeRate: number;
        disableACH: boolean;
        disableCard: boolean;
        taxRatesId: number;
        wallets: Wallet[];
        currencies: Currency[];
        accountEmail: string;
        confidenceLevel: number;
        requireShippingAddress: boolean;
        requireAccountInformation: boolean;
        status: string;
        currentStatus: any;
        redirectUrl: string;
        oneTimeUse: boolean;
        isReusable: boolean;
        minutesToExpire: number;
        isInvoice: boolean;
        processingFeeInversion: boolean;
        isProcessingFeeEnabled: boolean;
        dueDate: number;
        qbInvoiceId: string;
        hasBeenSyncedToQuickbooks: boolean;
    };
    wallets: Wallet[];
    id: number;
    metadata: string;
    enableCrypto: boolean;
    uniqueId: string;
    updateAccInfo: boolean;
    updateAddInfo: boolean;
    serviceFeeRate: number;
    isReusable: boolean;
    taxRatesId: number;
    processingFeeInversion: boolean;
    isProcessingFeeEnabled: boolean;
    requireAccountInformation: boolean;
    disableACH: boolean;
    disableCard: boolean;
    confidenceLevel: number;
    currentStatus: any;
    taxAmount: number;
    minutesToExpire: number;
    paymentLink: string;
    requireShippingAddress: boolean;
    redirectUrl: string;
    oneTimeUse: boolean;
    emailNotificationDisabled: boolean;
    accountId: number;
    status: string;
    reusableLinkId: number;
    accountEmail: string;
    products: Product[];
    currencies: Currency[];
    isInvoice: boolean;
    dueDate: number;
    qbInvoiceId: string;
    hasBeenSyncedToQuickbooks: boolean;
    protected objectType: string;
    constructor(pl?: Partial<PaymentLink>);
    static createInstanceLazy(acc: Partial<IPaymentLink>): Promise<PaymentLink>;
    static createInstanceSafe(acc: Partial<IPaymentLink>): Promise<PaymentLink>;
}
