import { FluxType } from './FluxType';
import { IQuickBooksIntegrationInformation } from './IQuickBooksIntegrationInformation';
export declare class QuickBooksIntegrationInformation extends FluxType implements IQuickBooksIntegrationInformation {
    obName: string;
    getDispName(): string;
    serialize(): {
        id: number;
        merchantId: number;
        accessToken: string;
        refreshToken: string;
        realmId: string;
        qbCustomerId: string;
        qbItemSale: string;
        qbItemRefund: string;
        qbItemChargeback: string;
        qbItemAdjustment: string;
        qbItemAuthFee: string;
        qbItemProcessingFee: string;
        qbExpenseAccountId: string;
        qbIncomeAccountId: string;
        qbIncomeItemId: string;
        qbBankAccountId: string;
        qbTaxLiabilityAccountId: string;
        qbTaxItemId: string;
        activeStatus: boolean;
        objectType: string;
    };
    id: number;
    merchantId: number;
    accessToken: string;
    refreshToken: string;
    realmId: string;
    qbCustomerId: string;
    qbItemSale: string;
    qbItemRefund: string;
    qbItemChargeback: string;
    qbItemAdjustment: string;
    qbItemAuthFee: string;
    qbItemProcessingFee: string;
    qbExpenseAccountId: string;
    qbIncomeAccountId: string;
    qbIncomeItemId: string;
    qbBankAccountId: string;
    qbTaxLiabilityAccountId: string;
    qbTaxItemId: string;
    activeStatus: boolean;
    protected objectType: string;
    constructor(qbInfo?: Partial<QuickBooksIntegrationInformation>);
}
