import { BaseQuery } from "./BaseQuery";
import { IRecurringTransactionQuery } from "./IRecurringTransactionQuery";
import { RecurringTransaction } from "./RecurringTransaction";
export declare class RecurringTransactionQuery extends BaseQuery<RecurringTransaction> implements IRecurringTransactionQuery {
    serialize(): {
        id: number;
        metadata: string;
        uniqueId: string;
        objectType: string;
        recurringAmount: number;
        recurringTaxAmount: number;
        originalTransactionId: number;
        productId: number;
        createdAt: number;
        isCurrent: boolean;
        accountId: number;
        productDumpId: number;
        otplId: number;
        status: any;
        cancelled: boolean;
        isInstallmentType: boolean;
        totalInstallments: number;
        installmentsLeft: number;
    };
    id: number;
    metadata: string;
    uniqueId: string;
    recurringAmount: number;
    accountId?: number;
    recurringTaxAmount: number;
    originalTransactionId: number;
    productId: number;
    isCurrent: boolean;
    productDumpId: number;
    otplId: number;
    status: any;
    cancelled: boolean;
    isInstallmentType: boolean;
    totalInstallments: number;
    installmentsLeft: number;
    objectType: string;
    constructor(tokQ?: IRecurringTransactionQuery);
    static createQuery(ipq: IRecurringTransactionQuery): RecurringTransactionQuery;
}
