import { FluxType } from './FluxType';
import { IRecurringTransaction } from './IRecurringTransaction';
import { PaymentLink } from './PaymentLink';
import { Transaction } from './Transaction';
export declare class RecurringTransaction extends FluxType implements IRecurringTransaction {
    obName: string;
    getDispName(): string;
    serialize(): {
        id: number;
        metadata: string;
        uniqueId: string;
        objectType: string;
        recurringAmount: number;
        recurringTaxAmount: number;
        originalTransactionId: number;
        accountId: number;
        productId: number;
        productDumpId: number;
        otplId: number;
        nextProcessDate: Date;
        paymentLinkId: number;
        paymentLink: PaymentLink;
        transactions: Transaction[];
        installmentPeriod: "MONTHLY" | "QUARTERLY" | "ANNUALLY";
        status: any;
        cancelled: boolean;
        isCurrent: boolean;
        isInstallmentType: boolean;
        totalInstallments: number;
        installmentsMade: number;
    };
    id: number;
    metadata: string;
    uniqueId: string;
    recurringAmount: number;
    recurringTaxAmount: number;
    nextProcessDate: Date;
    originalTransactionId: number;
    isCurrent: boolean;
    accountId: number;
    paymentLinkId: number;
    paymentLink: PaymentLink;
    transactions: Transaction[];
    productId: number;
    productDumpId: number;
    otplId: number;
    installmentPeriod: 'MONTHLY' | 'QUARTERLY' | 'ANNUALLY';
    status: any;
    cancelled: boolean;
    isInstallmentType: boolean;
    totalInstallments: number;
    installmentsMade: number;
    protected objectType: string;
    constructor(recurringTransaction?: Partial<RecurringTransaction>);
    static createInstanceLazy(acc: Partial<IRecurringTransaction>): Promise<RecurringTransaction>;
    static createInstanceSafe(acc: Partial<IRecurringTransaction>): Promise<RecurringTransaction>;
}
